### ISSUE TITLE
NP2 URL has changed

### ISSUE THREAD

**Issue by BrandonDusseau** [wrenoud/phpTriton#4]
The library has broken because the game's URL has changed from http://triton.ironhelmet.com to https://np.ironhelmet.com. I'm in the process of fixing this at this time.

**Comment by wrenoud** [comment]
If you make a pull request I’d be happy to approve it. Otherwise it will be at least a day before I can make that change.

**Comment by wrenoud** [comment]
Ah! Saw the commit after commenting.

**Comment by BrandonDusseau** [comment]
Yep, it should be up shortly after I finish testing it. :)
